POST http://localhost:3000/hikes/create
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiZ3VpZGUzIiwiaXNHdWlkZSI6dHJ1ZSwiaWF0IjoxNjk3MTAyMjg1LCJleHAiOjE2OTc3MDcwODV9.0hmnPPp7ecB0mmoYqwZktU_q4nbkjMQliK7PImsnLTg

{
    "name": "Uspon na trem3",
    "description": "Klasican uspon",
    "regionId": 1,
    "distance": 10000,
    "elevationGain": 1100,
    "travelCost": 2000,
    "date": "2023-10-15"
}
