### Create a new User
POST http://localhost:3000/auth/register
content-type: application/json

{
    "fullName": "trev trev2",
    "username": "trev2",
    "email": "treva@gmail.com",
    "password": "trev",
    "gender": "Other"
}